Add the missing structures
polaroi8d/jerryscript pull request #10
Opened 2016-11-09 10:30 UTC by polaroi8d

- We need 3 more structure for the debugger
	- Add the header types too

JerryScript-DCO-1.0-Signed-off-by: Levente Orban orbanl@inf.u-szeged.hu

2016-11-10 08:36 UTC, stampho requested changes

2016-11-10 08:36 UTC, stampho commented on jerry-core/debugger/jerry-debugger.h
> + * of the data come from the JerryScript. If the buffer size it's not enough for
size is not enough

2016-11-10 08:36 UTC, stampho commented on jerry-core/debugger/jerry-debugger.h
> + * the message the engine split up into many pieces. The last piece we know if the
1. splits it up into ...
2. The header of the last piece has a type with an '_END' postfix.

2016-11-10 08:36 UTC, stampho commented on jerry-core/debugger/jerry-debugger.h
> + * It can help for the debugger who can decide what type
This helps the debugger to decide ...

2016-11-10 08:36 UTC, stampho commented on jerry-core/debugger/jerry-debugger.h
> +  jerry_debugger_message_header_t header;       /**< header of the source file name struct */
1. I suppose the struct represents the message itself. So rather comment it with:
"header of the source file name message"
2. I'm not sure about the comment policy but personally I would keep it shorter:
"header of the message"
I think the header type name is very descriptive

2016-11-10 08:36 UTC, stampho commented on jerry-core/debugger/jerry-debugger.h
> +  char file_name[1];                            /**< the message which contains the source file name */
I would propose the same here: keep it shorter:
"source file name"
or
"JavaScript source file name"

2016-11-10 08:36 UTC, stampho commented on jerry-core/debugger/jerry-debugger.h
> +  char byte_code_cp[1];                        /**< breakpoint list */
1. the property name doesn't seem to match with the comment. Probably name it like this:

char byte_code_list[1];

2016-11-10 08:36 UTC, stampho commented on jerry-core/debugger/jerry-debugger.h
> +} jerry_debugger_message_source_name_t;
I'm not sure whether this can be compiled. This struct name seems to be duplicate: this is not the "source_name" but the "breakpoint_list" message

2016-11-11 08:31 UTC, zherczeg commented on jerry-core/debugger/jerry-debugger.h
> +  jerry_debugger_bp_pairs_t breakpoint_pairs[15];	/**< array of the breakpoint pairs */
The length should be:
1) 1 like in other cases
2) compute the maximum length from MAX_BUFFER_SIZE in ALL cases.

2016-11-17 13:12 UTC, zherczeg commented on jerry-core/debugger/jerry-debugger.h
> +#define COMPUTE_ITEM_COUNT(type) \
Please rename it to  JERRY_DEBUGGER_MAX_SIZE.
LGTM after this change.

2016-11-17 13:24 UTC, merged