Manage the FREE_BYTE_CODE_CPTR in client side
polaroi8d/jerryscript pull request #16
Opened 2017-01-04 07:59 UTC by polaroi8d

Remove element from the list which has the given `cptr` key. 

JerryScript-DCO-1.0-Signed-off-by: Levente Orban orbanl@inf.u-szeged.hu

2017-01-04 15:07 UTC, zherczeg commented on jerry-debugger/jerry-client.py
> -    function_list = []
JerryDebuger should be an entity, so there is no point to take this out to global level. Global variables are not recommended in general.

2017-01-04 15:09 UTC, zherczeg commented on jerry-debugger/jerry-client.py
> +                           JERRY_DEBUGGER_FREE_BYTE_CODE_CPTR]:
Byte code free should not be handled by the parser, it should be an independent event.

2017-01-04 15:09 UTC, zherczeg commented on jerry-debugger/jerry-client.py
> -            print(data[2:buffer_size+2])
Exactly like this.

2017-01-05 07:40 UTC, polaroi8d commented
Thanks @zherczeg for reviewing in your free time, I'm updated the PR following your reflection.

2017-01-13 08:42 UTC, polaroi8d commented on jerry-debugger/jerry-client.py
> +    debugger.function_list = list(function_list_tmp) # Copy the ready list to the global storage
new_function_lisr

2017-01-13 08:42 UTC, polaroi8d commented on jerry-debugger/jerry-client.py
> +            print('Empty stack!')
Míake them comments, add a log function later.

2017-01-13 08:42 UTC, polaroi8d commented on jerry-debugger/jerry-client.py
> +        self.function_list = []
This should be a dictionary, where the key is the cptr.

2017-01-13 12:08 UTC, zherczeg requested changes
LGTM after the main-unix change is removed.

2017-01-13 12:08 UTC, zherczeg commented on jerry-main/main-unix.c
> +  jerry_debugger_send_type (JERRY_DEBUGGER_PARSE_FUNCTION);
We really shouldn't need to send this low level message here. If we need, there is some bug in the code.

2017-01-16 08:18 UTC, polaroi8d commented on jerry-main/main-unix.c
> +  jerry_debugger_send_type (JERRY_DEBUGGER_PARSE_FUNCTION);
Okey.

2017-01-16 08:19 UTC, merged