Push CBC_BREAKPOINT to the opcode list
polaroi8d/jerryscript pull request #4
Opened 2016-10-27 16:00 UTC by polaroi8d

Detect the statement lines and add breakpoints to the bytecode list.

JerryScript-DCO-1.0-Signed-off-by: Levente Orban orbanl@inf.u-szeged.hu

2016-10-28 07:36 UTC, zherczeg commented on jerry-core/parser/js/js-parser.c
> +  context.statement_line = 0;
When this context.statement_line is updated? I only saw one setting here.

2016-10-28 12:52 UTC, zherczeg commented on jerry-core/parser/js/js-parser-statm.c
> +    if (context_p->line != context_p->statement_line)
There is no check whether debugger is enabled during init.

2016-11-01 18:35 UTC, polaroi8d commented on jerry-core/parser/js/js-parser-statm.c
> +    if (context_p->line != context_p->statement_line)
@zherczeg you think about this one `if (JERRY_CONTEXT (jerry_init_flags) & JERRY_INIT_DEBUGGER)` ?

2016-12-09 07:43 UTC, zherczeg commented on jerry-core/parser/js/js-parser-statm.c
> +    /* Add breakpoints, after every single line. This breakpoints has an
Breakpoints should be added before every line :) When the line starts.

2016-12-09 07:44 UTC, zherczeg commented on jerry-core/parser/js/js-parser-statm.c
> +    parser_emit_cbc (context_p, CBC_BREAKPOINT);
First, we need to check whether debugging is enabled, and we should insert NOP-s, which can be turned to debugger at any point by the debugger.

2016-12-12 09:24 UTC, polaroi8d commented on jerry-core/parser/js/js-parser-statm.c
> +    parser_emit_cbc (context_p, CBC_BREAKPOINT);
You think to add a `parser_emit_cbc(context_p, CBC_EXT_NOP);` ?

2016-12-12 09:29 UTC, polaroi8d commented on jerry-core/parser/js/js-parser-statm.c
> +    /* Add breakpoints, after every single line. This breakpoints has an
Okey.

2016-12-13 09:45 UTC, zherczeg requested changes

2016-12-13 09:45 UTC, zherczeg commented on jerry-core/parser/js/byte-code.h
> +  CBC_OPCODE (CBC_BREAKPOINT_DESABLE, CBC_NO_FLAG, 0, \
CBC_BREAKPOINT_ENABLED CBC_BREAKPOINT_DISABLED

2016-12-13 09:45 UTC, zherczeg commented on jerry-core/parser/js/js-parser-statm.c
> +    /* Add breakpoints, before every single line. We have two tpye of breakpoints
type

2016-12-13 09:45 UTC, zherczeg commented on jerry-core/parser/js/js-parser-statm.c
> +    *  one of them the active (enable) others the inactive (desable). In basic
enabled, disabled

2016-12-13 12:12 UTC, polaroi8d commented on jerry-core/parser/js/js-parser-statm.c
> +    *  one of them the active (enable) others the inactive (desable). In basic
Thanks for the review, updated the PR.

2016-12-13 14:08 UTC, zherczeg commented on jerry-core/parser/js/js-parser-statm.c
> +      parser_flush_cbc(context_p);
It seems you add a breakpoint before each statement. You should only do it before each line according to the comment above.

2016-12-19 09:18 UTC, zherczeg requested changes

2016-12-19 09:18 UTC, zherczeg commented on jerry-core/parser/js/js-parser-internal.h
> +  parser_line_counter_t last_bp_line;         /**< last line where breakpoint was inserted */
last_breakpoint_line

2016-12-19 09:18 UTC, zherczeg commented on jerry-core/parser/js/js-parser-statm.c
> +          && context_p->token.type != LEXER_KEYW_FUNCTION)
Add case and default keywords here.

2016-12-19 12:01 UTC, zherczeg commented
LGTM

2016-12-19 12:03 UTC, merged