Add the structure of the debugger package
polaroi8d/jerryscript pull request #5
Opened 2016-10-27 17:32 UTC by polaroi8d

Add the structures what the debugger will be use. 

JerryScript-DCO-1.0-Signed-off-by: Levente Orban orbanl@inf.u-szeged.hu

2016-10-28 07:36 UTC, zherczeg commented on jerry-core/debugger/debugger.h
> +#endif /* JERRY_DEBUG_H */
Should be /* JERRY_DEBUGGER_H */

2016-10-28 07:37 UTC, zherczeg commented on jerry-core/debugger/debugger.h
> +/* Copyright 2016 University of Szeged.
The file name should be jerry-debug.h

2016-10-28 07:37 UTC, zherczeg commented on jerry-core/debugger/debugger.h
> +/* Copyright 2016 University of Szeged.
Or jerry-debugger.h

2016-10-28 07:37 UTC, zherczeg commented on jerry-core/debugger/debugger.h
> +#define JERRY_DEBUGGER_H
This must come from the file name.

2016-10-28 07:44 UTC, zherczeg commented on jerry-core/debugger/debugger.h
> +  uint16_t count;             /**< line count */
There should not be packed everything into one structure. The layout should look like this (without comments):

    typdef struct
    {
      uint8_t type;
      uint8_t size;
    } jerry_debug_message_header;

And each message should have its own type.

    typdef struct
    {
      jerry_debug_message_header header;
      char file_name[1];
    } jerry_debug_message_source_name;

One structure for each message.

Perhaps SOURCE_FILE type is enough for this patch.

2016-10-28 07:45 UTC, zherczeg commented on jerry-core/debugger/debugger.h
> +  package_type_t type;        /**< type of the package */
We never use types with unspecified length for network messages because the compiler might use types for them.

2016-10-28 10:32 UTC, polaroi8d commented
Updated the PR.

2016-11-02 07:53 UTC, zherczeg commented on jerry-core/debugger/jerry-debugger.h
> +  char file_name[128];                  /**< the message */
The file name should be 1 character long, and the real name should adapt the size

2016-11-03 08:43 UTC, stampho requested changes

2016-11-03 08:43 UTC, stampho commented on jerry-core/debugger/jerry-debugger.h
> +  char file_name[1];                    /**< the message */
This is definetely wrong. This means 1 character long string.

2016-11-07 08:51 UTC, zherczeg commented on jerry-core/debugger/jerry-debugger.h
> +  char file_name[1];                    /**< the message */
No, this is correct.

This struct is a mapping struct, mapped to a buffer, and the maximum buffer size limits the file_name.

2016-11-07 08:52 UTC, zherczeg commented
LGTM

2016-11-07 09:06 UTC, merged