Add jerry-client.py
polaroi8d/jerryscript pull request #8
Opened 2016-11-07 08:22 UTC by polaroi8d

Add the client side of the communication to debugger. 

JerryScript-DCO-1.0-Signed-off-by: Levente Orban orbanl@inf.u-szeged.hu

2016-11-07 08:49 UTC, zherczeg commented on jerry-debugger/jerry-client.py
> +    print ('Socket created on: %d'% PORT)
What is the style: space or not space after print?

2016-11-07 08:51 UTC, polaroi8d commented on jerry-debugger/jerry-client.py
> +    print ('Socket created on: %d'% PORT)
Without space, thanks.

2016-11-07 08:52 UTC, stampho requested changes

2016-11-07 08:52 UTC, stampho commented on jerry-debugger/jerry-client.py
> +        sys.exit()
Return code is missing from here. Probably use sys.exit(1) or you might use the error code above but not sure whether is this the common way to do this.

Hint: you can easily check the sys.exit() usage in the Jerry's python scripts with the following command:
find . -name "*.py" | xargs grep --color "sys.exit"

2016-11-07 08:52 UTC, stampho commented on jerry-debugger/jerry-client.py
> +    print ('Socket created on: %d'% PORT)
nitpick: style issues with space:
1. print (
2. %d'%

2016-11-07 08:54 UTC, stampho commented on jerry-debugger/jerry-client.py
> +        print('Failed to create the socket. Error code: %d, Error message: %s' % (msg[0], msg[1]))
on more thing: probably you should send error message to the stderr. Check sys.stderr.write in the python documentation.

2016-11-07 09:13 UTC, polaroi8d commented on jerry-debugger/jerry-client.py
> +        sys.exit()
Thanks for the instruction.

2016-11-07 09:18 UTC, polaroi8d commented on jerry-debugger/jerry-client.py
> +    print ('Socket created on: %d'% PORT)
:+1:

2016-11-07 09:18 UTC, polaroi8d commented on jerry-debugger/jerry-client.py
> +        print('Failed to create the socket. Error code: %d, Error message: %s' % (msg[0], msg[1]))
Okey.

2016-11-07 10:37 UTC, stampho commented on jerry-debugger/jerry-client.py
> +        print >> sys.stderr, ('Failed to create the socket. Error code: %d, Error message: %s' % (msg[0], msg[1]))
Most probably this won't work with python3. I would propose to use sys.stderr.write('message\n')

Anyway, I've just found something: http://stackoverflow.com/questions/2949974/how-to-exit-a-program-sys-stderr-write-or-print

It seems sys.exit('message') is a proposed way and exits with exit code 1

2016-11-07 14:44 UTC, stampho commented
LGTM

2016-11-08 11:03 UTC, zherczeg commented
LGTM

2016-11-08 11:07 UTC, merged